import React from 'react';
import ReactMarkdown from 'react-markdown';
import { motion } from 'framer-motion';
import { FileText, Download } from 'lucide-react';

interface ReportViewerProps {
  report: string;
}

const ReportViewer: React.FC<ReportViewerProps> = ({ report }) => {
  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="flex flex-col h-full bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"
    >
      {/* 리포트 헤더 */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-gray-50 bg-gray-50/30">
        <div className="flex items-center gap-2">
          <FileText size={20} className="text-gray-400" />
          <h2 className="font-bold text-gray-700">심층 분석 리포트</h2>
        </div>
        <button
          onClick={() => window.print()}
          className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-500 hover:bg-white hover:shadow-sm rounded-lg transition-all"
        >
          <Download size={14} />
          PDF 저장
        </button>
      </div>

      {/* 리포트 본문 (Markdown) */}
      <div className="flex-1 overflow-y-auto p-8 custom-scrollbar">
        <div className="max-w-none prose prose-blue prose-headings:font-black prose-p:text-gray-600 prose-li:text-gray-600">
          <ReactMarkdown
            components={{
              h1: ({ node, ...props }) => <h1 className="text-3xl font-black text-gray-900 mb-6 border-b-2 border-gray-100 pb-2" {...props} />,
              h2: ({ node, ...props }) => <h2 className="text-xl font-bold text-gray-800 mt-8 mb-4 flex items-center gap-2 before:content-[''] before:w-1 before:h-6 before:bg-blue-500 before:rounded-full" {...props} />,
              h3: ({ node, ...props }) => <h3 className="text-lg font-semibold text-gray-700 mt-6 mb-2" {...props} />,
              p: ({ node, ...props }) => <p className="leading-relaxed mb-4 text-gray-600" {...props} />,
              li: ({ node, ...props }) => <li className="mb-1 text-gray-600 list-disc ml-4" {...props} />,
              strong: ({ node, ...props }) => <strong className="font-bold text-gray-900" {...props} />,
              blockquote: ({ node, ...props }) => (
                <blockquote className="border-l-4 border-blue-200 bg-blue-50/50 p-4 my-6 italic text-gray-700 rounded-r-lg" {...props} />
              ),
            }}
          >
            {report}
          </ReactMarkdown>
        </div>
      </div>

      {/* 푸터 (전문성 강조) */}
      <div className="px-8 py-4 bg-gray-50/50 text-[10px] text-gray-400 border-t border-gray-50 uppercase tracking-widest">
        Generated by Himidea AI Multi-Agent Engine • Seogyo-dong Context v1.0
      </div>
    </motion.div>
  );
};

export default ReportViewer;
